### ISSUE TITLE
IllegalAccessError with enum properties of facts

### ISSUE THREAD

**Issue by dmfay** [andbi/evrete#14]
Sample code (everything in one file for convenience, in the original context both MyEnum and ThingWithEnum are public):

```java
package org.etc.etc;

import org.evrete.KnowledgeService;
import org.evrete.api.*;
import org.evrete.dsl.annotation.Fact;
import org.evrete.dsl.annotation.Rule;
import java.io.IOException;

enum MyEnum {one, two, three};

class ThingWithEnum {
    private MyEnum enumVal;

    public ThingWithEnum(final MyEnum enumVal) { this.enumVal = enumVal; }

    public MyEnum getEnumVal() { return enumVal; }
}

public class TestService {
    private static final KnowledgeService knowledgeService = new KnowledgeService();

    public static class Ruleset {
        @Rule
        public static void trySomething(final RhsContext ctx, @Fact("$coverage") final ThingWithEnum twe) {
            switch (twe.getEnumVal()) {
                case one: System.out.println("it's one!"); break;
                case two: System.out.println("it's two!"); break;
                default: break;
            }
        }
    }

    public static void doTheThing() throws IOException {
        final Knowledge knowledge = knowledgeService.newKnowledge("JAVA-CLASS", Ruleset.class);
        final StatefulSession session = knowledge.newStatefulSession(ActivationMode.CONTINUOUS);

        session.insert(new ThingWithEnum(MyEnum.one));
        session.fire();
    }
}
```

does this:

```
java.lang.RuntimeException: java.lang.IllegalAccessError: tried to access class org.etc.etc.TestService$1 from class org.etc.etc.TestService$Ruleset

	at org.evrete.dsl.ClassMethod.call(ClassMethod.java:68)
	at org.evrete.dsl.RuleMethod.accept(RuleMethod.java:90)
	at org.evrete.dsl.RuleMethod.accept(RuleMethod.java:14)
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at org.evrete.runtime.RuntimeRuleImpl.forEachFact(RuntimeRuleImpl.java:148)
	at org.evrete.runtime.RuntimeRuleImpl.forEachKey(RuntimeRuleImpl.java:126)
	at org.evrete.runtime.RuntimeRuleImpl.forEachFactGroup(RuntimeRuleImpl.java:109)
	at org.evrete.runtime.RuntimeRuleImpl.callRhs(RuntimeRuleImpl.java:91)
	at org.evrete.runtime.AbstractRuleSessionIO.fireContinuous(AbstractRuleSessionIO.java:100)
	at org.evrete.runtime.AbstractRuleSessionIO.fireInner(AbstractRuleSessionIO.java:30)
	at org.evrete.runtime.StatefulSessionImpl.fire(StatefulSessionImpl.java:39)
	at org.evrete.dsl.DSLStatefulSession.fire(DSLStatefulSession.java:19)
	at org.etc.etc.TestService.doTheThing(TestService.java:38)
	at org.etc.etc.TestServiceTests.doTheThing(TestServiceTests.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
  <all junit/intellij from here down>
Caused by: java.lang.IllegalAccessError: tried to access class org.etc.etc.TestService$1 from class org.etc.etc.TestService$Ruleset
	at org.etc.etc.TestService$Ruleset.trySomething(TestService.java:25)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.evrete.dsl.ClassMethod.call(ClassMethod.java:64)
	... 82 more
```

Changing the switch condition to `twe.getEnumVal().toString()` and comparing that to strings in the switch body _does_ work though! I had noticed just a little bit ago that Evrete didn't want to compile an LHS with direct enum comparisons (`@Where("$twe.enumVal == MyEnum.one")`) but in that instance it just can't find the symbol, which I assume is because it's got its own independent compile step. Again using `toString()` gets through it and the LHS works fine.

**Comment by andbi** [comment]
My guess it's a visibility problem, making classes public (including the enum) should solve the issue. 

With annotated Java rules, Evrete executes RHS methods as if they're called from within the ruleset class. So the solution would be either making the enum public, or placing it inside the ruleset class.

**Comment by dmfay** [comment]
The original ThingWithEnum class and MyEnum are both public, Java just won't compile a public class/enum if it isn't in a dedicated file :/ Same IllegalAccessError occurs if you try moving them out.

**Comment by andbi** [comment]
Looks like another bug with classloaders and protection domains. The root problem here is that, in order to support Java Security Manager, Evrete is redefining classes which sometimes results in a conflict with existing ones.

As far as I remember, the trading showcase uses enums without any problems. Ruleset class statically imports enum values and uses them in conditions as-is, w/o unnecessary `toString()` calls and `equals()` instead of `==`.
